version: '2.2' 
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    networks:
      - homeserver
    restart: unless-stopped 
    ports:
      - '80:80'
      - '81:81'
      - '443:443' 
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt 

networks:
  homeserver:
    name: homeserver

volumes:
  data:
    driver: local
  letsencrypt:
    driver: local
